#!/bin/sh

BASEDIR="$(dirname $)"

node="$BASEDIR/vendor/node-v12.16.1-linux-x64/bin/node"

npm () {
  "$node" "$BASEDIR/vendor/node-v12.16.1-linux-x64/lib/node_modules/npm/bin/npm-cli.js" $@;
}

npm start > /dev/null 2>&1 || rm -rf "$BASEDIR/node_modules" && npm install && npm start
